CREATE TABLE `cometRenderTasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`providerTaskId` varchar(240) NOT NULL,
	`renderAssetId` int,
	`kind` enum('wreath','lifestyle') NOT NULL,
	`operation` varchar(40) NOT NULL,
	`model` varchar(160),
	`status` enum('queued','submitting','polling','completed','failed','review_ready') NOT NULL DEFAULT 'queued',
	`progress` int NOT NULL DEFAULT 0,
	`message` text,
	`sceneIndex` int,
	`sceneTitle` varchar(180),
	`errorMessage` text,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cometRenderTasks_id` PRIMARY KEY(`id`)
);
