import type { BlueprintObject, FloralItem } from "./composition";

export type BuildSheetInput = {
  blueprint: { schema: string; version: string; sizeIn: number; formula: string; seed: number; emotion: string; silenceArc: [number, number]; ringBands: Array<{ name: string; radius: number; role: string }>; clusters: Record<string, string[]>; objects: BlueprintObject[] };
  items: FloralItem[];
  title?: string;
};

export function buildPrintableBuildSheet({ blueprint, items, title = "Evercrafted memory wreath build sheet" }: BuildSheetInput) {
  const names = new Map(items.map((item) => [item.itemId, item.name]));
  const objectRows = blueprint.objects.map((object) => `<tr><td>${object.id}</td><td>${names.get(object.asset) ?? object.asset}</td><td>${object.layer}</td><td>${object.theta}°</td><td>${object.radius.toFixed(2)}</td><td>${object.rotation}°</td></tr>`).join("");
  const bands = blueprint.ringBands.map((band) => `<li><strong>${band.name}</strong> · ${band.role} · radius ${band.radius}</li>`).join("");
  const clusters = Object.entries(blueprint.clusters).map(([name, ids]) => `<li><strong>${name}</strong> · ${ids.join(", ")}</li>`).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>body{font:14px Georgia,serif;color:#26342b;max-width:900px;margin:40px auto;padding:0 28px}h1{font-size:38px;font-weight:400;margin-bottom:4px}h2{font-size:19px;font-weight:400;border-bottom:1px solid #cbbda6;padding-bottom:8px;margin-top:32px}p,li{line-height:1.6}table{border-collapse:collapse;width:100%;font:12px ui-monospace,monospace}th,td{border-bottom:1px solid #ddd3c5;padding:8px;text-align:left}th{background:#f1ece2;text-transform:uppercase;font-size:10px;letter-spacing:.08em}.meta{color:#806b4a;font:11px ui-monospace,monospace;text-transform:uppercase;letter-spacing:.08em}@media print{body{margin:0;max-width:none}.no-print{display:none}}</style></head><body><p class="meta">${blueprint.schema} · v${blueprint.version} · seed ${blueprint.seed}</p><h1>${title}</h1><p class="meta">${blueprint.emotion} · ${blueprint.formula} · ${blueprint.sizeIn} inch wreath</p><h2>Build notes</h2><p>Protect the silence arc from ${blueprint.silenceArc[0]}° to ${blueprint.silenceArc[1]}°. Place greenery first, then filler, secondary, and focal anchors. Follow the ring bands and clock positions below.</p><h2>Ring bands</h2><ul>${bands}</ul><h2>Clusters</h2><ul>${clusters}</ul><h2>Placement schedule</h2><table><thead><tr><th>ID</th><th>Material</th><th>Layer</th><th>Clock angle</th><th>Radius</th><th>Rotation</th></tr></thead><tbody>${objectRows}</tbody></table><p class="meta">Generated by Evercrafted · renderer-agnostic build artifact</p></body></html>`;
}

export function buildSheetFilename(seed: number) { return `evercrafted-build-sheet-${seed}.html`; }
